## arg 1:  the new package version
#pre_install() {
	# do something here
#}

## arg 1:  the new package version
post_install() {
    bash /usr/share/libalpm/scripts/plasma-appsmenu-biglinux-icon
}

## arg 2:  the old package version
#pre_upgrade() {
	# do something here
#}

## arg 2:  the old package version
post_upgrade() {
	post_install
}

## arg 1:  the old package version
#pre_remove() {
	# do something here
#}

## arg 1:  the old package version
#post_remove() {
	# do something here
#}
 
